---
title: "R Notebook"
output: html_notebook
---
# Project 2 - Shiny App

Data Processing
```{r, echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = TRUE) 
```

```{r}
# Load libraries needed
library(tidyverse)
library(lubridate)
```

```{r}
License_Application <- read_csv("data/License_Applications.csv")
dim(License_Application);names(License_Application)

License_App <- License_Application %>% filter(State == "NY") %>%
  mutate(Start_date = mdy(`Start Date`), End_date = mdy(`End Date`), City = tolower(City)) %>%
  dplyr::select(Start_date, End_date, `Application ID`, `License Number`, `License Type`,
                `Application or Renewal`,`Business Name`,Status,`License Category`,`Application Category`,`Building Number`,Street,City,State,Zip,Longitude,Latitude) %>% filter(Start_date >= as.Date("2017-01-01")) %>%
  arrange(Start_date) 
```
Five boroughs in new york are Brooklyn, Bronx, Manhattan,Queens, State Island.
Queens indicated as "queens village" or "queens vlg" 

```{r}
NYC_License <- License_App %>% filter(City %in% c("bronx","brooklyn","new york",
                                                  "staten island", "manhattan", "queens village", "queens vlg"))

#Category count by month
License_by_month <- NYC_License %>% group_by(month = floor_date(Start_date,"month"),`Application or Renewal`,`License Category`) %>% summarise(cnt = n()) %>% 
  arrange(month)


#Category_cnt of License Application
Category_cnt <- NYC_License %>% group_by(year = floor_date(Start_date,"year"),`Application or Renewal`,`License Category`) %>% summarise(cnt = n()) %>% 
  arrange(year, desc(cnt))

#total_app_by_year <- License_App %>% group_by(year = floor_date(Start_date,"year"),`Application or Renewal`) %>% summarise(cnt = n()) %>% 
#  arrange(year)
#total_app


total_app_by_month <- 
 License_App %>% group_by(month = floor_date(Start_date,"month"),`Application or Renewal`) %>% summarise(cnt = n()) %>% 
  arrange(month)

ggplot(total_app_by_month, aes(x = month, y = cnt)) +
  geom_line(aes(color = `Application or Renewal`)) +
  labs(y = "Number of License renewed and applied in month") +
  scale_x_date(breaks = "4 month") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) 
```



# Implement covid data
```{r}
Covid_19_raw <- read_csv("data/COVID-19.csv")
dim(Covid_19_raw);names(Covid_19_raw)

Covid_19 <- Covid_19_raw %>% mutate(Date = mdy(DATE_OF_INTEREST), .before = DATE_OF_INTEREST) %>%
  dplyr::select(Date, CASE_COUNT,probable_case_count, HOSPITALIZED_COUNT,DEATH_COUNT,
                DEATH_COUNT_PROBABLE,CASE_COUNT_7DAY_AVG,all_case_count_7day_avg,
                HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,all_death_count_7day_avg)
  
```

### Impact by covid ? How covid 19 affect application? 
Join two tables

```{r}
#covid 19 count by month, case count and death count,Date, CASE_COUNT,probable_case_count, HOSPITALIZED_COUNT,DEATH_COUNT,DEATH_COUNT_PROBABLE
Covid_by_month <- Covid_19 %>% group_by(month = floor_date(Date,"month")) %>% 
  summarise(monthly_case_count = sum(CASE_COUNT), monthly_death = sum(DEATH_COUNT), monthly_hospitalized = sum(HOSPITALIZED_COUNT),
            monthly_case_probable = sum(probable_case_count), monthly_death_probable = sum(DEATH_COUNT_PROBABLE)) %>% 
  arrange(desc(month))

Category_by_month <- NYC_License %>%
  group_by(month = floor_date(Start_date,"month"),
           `Application or Renewal`,`License Category`) %>%
  summarise(License_cnt = n()) %>% 
  arrange(month)


Month_Application_Covid <- Category_by_month %>%
  inner_join(Covid_by_month, by = c("month" = "month"))

```

1.covid cases vs total applications
2.covid cases vs category applications
```{r}
if (!require("plotly")) install.packages("plotly")
if (!require("viridis")) install.packages("viridis")
if (!require("hrbrthemes")) install.packages("hrbrthemes")
library(plotly)
library(viridis)
library(hrbrthemes)

data %>% arrange(desc(License_cnt))


#covid cases vs category applications
#The dataset is provided in the gapminder library
#data <- Month_Application_Covid %>% filter(`Application or Renewal` == "Application", `License Category` %in% c("Home Improvement Contractor"))
#p <- data %>% 
#  mutate(text = paste("Date:",month,"\nCovid_19 cases:",monthly_case_count,"\nApplications:",License_cnt,"\nLicense Category:",`License Category`, sep = "")) %>%
#  ggplot(aes(x=month,y=monthly_case_count,size = License_cnt, color = `License Category`,text = text))+
#  geom_point(alpha=0.7) +
#  geom_line(aes(y = monthly_case_count)) +
#  scale_size(range = c(1.4, 19), name="Population (M)") +
#  scale_color_viridis(discrete=TRUE, guide=FALSE) +
#  theme_ipsum() +
#  theme(legend.position="none")

#pp <- ggplotly(p, tooltip="text")
# pp

#covid cases vs total applications
data2 <- Month_Application_Covid %>% filter(`Application or Renewal` == "Application") %>% 
  group_by(month) %>%
  summarise(applications = sum(License_cnt), monthly_case_count=mean(monthly_case_count))
data2



p2 <- data2 %>% 
  mutate(text = paste("Date:",month,"\nCovid_19 cases:",monthly_case_count,"\nApplications:",applications, sep = "")) %>%
  ggplot(aes(x=month,y=monthly_case_count,size = applications, color = "lightgreen",text = text))+
  geom_point(alpha=0.7) +
  geom_line(aes(y = monthly_case_count)) +
  scale_size(range = c(1.4, 19), name="Population (M)") +
  scale_color_viridis(discrete=TRUE, guide=FALSE) +
  theme_ipsum() +
  theme(legend.position="none")

pp2 <- ggplotly(p2, tooltip="text")
pp2


```



# App Template
```{r}
if (!require("shiny")) install.packages("shiny")
library(shiny)
```

```{r}

data <- Month_Application_Covid %>% filter(`Application or Renewal` == "Application") %>% 
  mutate(text = paste("Date:",month,"\nCovid_19 cases:",monthly_case_count,"\nApplications:",License_cnt,"\nLicense Category:",`License Category`, sep = "")) %>%
  

var <- unique(License_by_month$`License Category`)

yr <- c("2022","2021","2020","2019","2018","2017")

shinyUI <- fluidPage(
  titlePanel("Applications of Different License Category"),
  sidebarLayout(position = "left",
                
  sidebarPanel(
    selectInput("year",label = "Select year", choices = yr, selected = "2017", multiple = F),
    selectInput("category", label= "Select a License Category", choices = var,
  selected = "Electronics Store", multiple = T)
      ),
  mainPanel(
    plotOutput("hist"),
    plotOutput('plot',hover  = "plot_hover"),
        verbatimTextOutput("info"),
    plotlyOutput('plot1')

          )
  )
)
  
#server.R
shinyServer<- function(input, output) {
  
  output$hist <- renderPlot({
    
  ggplot(data = filter(Category_cnt,year(year) == !!input$year ),aes(x = `License Category`, y = cnt, fill = `Application or Renewal`)) + 
  geom_col() + 
  labs(y = "Number of Applications or Renewals ",
       title = "Application and Renewal for License Category") +
  theme(axis.text.x = element_text(angle = 90, size = 10)) 

    
  })
  
  
  
  output$plot <-  renderPlot({
    ggplot(data = filter(License_by_month,`License Category` == !!input$category),aes(x = month, y = cnt,color = `Application or Renewal`)) +
    geom_point() +
             geom_line() +
    labs(title = "Applications and Renewals for License categories",
         x = "month",
         y = "Number of Applications or Renewals") +
    scale_x_date(breaks = "4 month") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
  })
  
  
  output$info <- renderText({
    input$plot_hover$y
  })
  
  output$plot1 <- renderPlotly({
  ggplotly(ggplot(data = filter(data,`License Category` == !!input$category),aes(x=month,y=monthly_case_count,size = License_cnt, color = `License Category`,text = text))+
  geom_point(alpha=0.7) +
  geom_line(aes(y = monthly_case_count)) +
  scale_size(range = c(0.5, 12), name="Applications") +
  scale_color_manual(values = c("#E7B800")) +
  labs(title = "Applications under Covid_19",
       y = "Covid_19 Monthly Case Count") +
  theme_ipsum() +
  theme(legend.position="none"), tooltip = "text" )

  })
  
  
  }
shinyApp(ui = shinyUI, server = shinyServer)


```


