---
title: "Timeseries"
author: "Ke Liu"
date: "2022/2/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
theme_set(theme_light())
```

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)

setwd("E:/cu/ads/pj2")
df0 <- read.csv('License_Applications.csv')
covid <- read.csv('COVID-19_Daily_Counts_of_Cases.csv')
covid <- covid %>% select(DATE_OF_INTEREST,CASE_COUNT) %>%
  mutate(DATE_OF_INTEREST = mdy(DATE_OF_INTEREST)) %>%
  rename(date = DATE_OF_INTEREST, case = CASE_COUNT)

covid_1 <- covid %>% 
  mutate(date = format(as.Date(date),'%Y-%m'), case = case/100) %>%
  group_by(date) %>%
  mutate(n = sum(case)) %>%
  select(date, n) %>%
  unique()

covid_20 <- covid %>% filter(year(date) == 2020) %>%
  mutate(date = format(as.Date(date),'%Y-%m'), case = case/100) %>%
  group_by(date) %>%
  mutate(n = sum(case)) %>%
  select(date, n) %>%
  unique()

covid_21 <- covid %>% filter(year(date) == 2021) %>%
  mutate(date = format(as.Date(date),'%Y-%m'), case = case/100) %>%
  group_by(date) %>%
  mutate(n = sum(case)) %>%
  select(date, n) %>%
  unique()

covid_22 <- covid %>% filter(year(date) == 2022) %>%
  mutate(date = format(as.Date(date),'%Y-%m'), case = case/100) %>%
  group_by(date) %>%
  mutate(n = sum(case)) %>%
  select(date, n) %>%
  unique()

df <- df0 %>% mutate(Start.Date = mdy(Start.Date), End.Date = mdy(End.Date))
df <- df %>% filter(year(Start.Date) >= 2017, State == 'NY')
df <- df %>% select(Application.ID, Start.Date, License.Type, Application.or.Renewal, Status, Application.Category)
df_1 <- df %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

df_0 <- df %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_17 <- df %>% filter(year(Start.Date) == 2017) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_18 <- df %>% filter(year(Start.Date) == 2018) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_19 <- df %>% filter(year(Start.Date) == 2019) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_20 <- df %>% filter(year(Start.Date) == 2020) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_21 <- df %>% filter(year(Start.Date) == 2021) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

df_22 <- df %>% filter(year(Start.Date) == 2022) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m')) %>%
  select(Start.Date)

#0.all all
g0_0 <- ggplot() + geom_bar(data = df_0, aes(x = Start.Date), fill = '#6699CC') + 
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g0_17 <- ggplot() + geom_bar(data = df_17, aes(x = Start.Date),fill = '#6699CC')
g0_18 <- ggplot() + geom_bar(data = df_18, aes(x = Start.Date),fill = '#6699CC')
g0_19 <- ggplot() + geom_bar(data = df_19, aes(x = Start.Date),fill = '#6699CC')
g0_20 <- ggplot() + geom_bar(data = df_20, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g0_21 <- ggplot() + geom_bar(data = df_21, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g0_22 <- ggplot() + geom_bar(data = df_22, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

ggarrange(g0_17, g0_18, g0_19, g0_20, g0_21, g0_22,
          labels = c("2017","2018","2019","2020","2021","2022"),
          ncol = 3, nrow = 2)
```

```{r}
#1.busi all
busi <- df %>% filter(License.Type == 'Business') %>%
  select(Start.Date, Application.Category, Application.or.Renewal) 

busi_0 <- busi %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_17 <- busi %>% filter(year(Start.Date) == 2017) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_18 <- busi %>% filter(year(Start.Date) == 2018) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_19 <- busi %>% filter(year(Start.Date) == 2019) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_20 <- busi %>% filter(year(Start.Date) == 2020) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_21 <- busi %>% filter(year(Start.Date) == 2021) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

busi_22 <- busi %>% filter(year(Start.Date) == 2022) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

g1_0 <- ggplot() + geom_bar(data = busi_0, aes(x = Start.Date), fill = '#6699CC') + 
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g1_17 <- ggplot() + geom_bar(data = busi_17, aes(x = Start.Date),fill = '#6699CC')
g1_18 <- ggplot() + geom_bar(data = busi_17, aes(x = Start.Date),fill = '#6699CC')
g1_19 <- ggplot() + geom_bar(data = busi_17, aes(x = Start.Date),fill = '#6699CC')
g1_20 <- ggplot() + geom_bar(data = busi_20, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g1_21 <- ggplot() + geom_bar(data = busi_21, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g1_22 <- ggplot() + geom_bar(data = busi_22, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#2.indi all
indi <- df %>% filter(License.Type == 'Individual') %>%
  select(Start.Date, Application.Category, Application.or.Renewal) 

indi_0 <- indi %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_17 <- indi %>% filter(year(Start.Date) == 2017) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_18 <- indi %>% filter(year(Start.Date) == 2018) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_19 <- indi %>% filter(year(Start.Date) == 2019) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_20 <- indi %>% filter(year(Start.Date) == 2020) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_21 <- indi %>% filter(year(Start.Date) == 2021) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

indi_22 <- indi %>% filter(year(Start.Date) == 2022) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

g2_0 <- ggplot() + geom_bar(data = indi_0, aes(x = Start.Date), fill = '#6699CC') + 
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g2_17 <- ggplot() + geom_bar(data = indi_17, aes(x = Start.Date),fill = '#6699CC')
g2_18 <- ggplot() + geom_bar(data = indi_17, aes(x = Start.Date),fill = '#6699CC')
g2_19 <- ggplot() + geom_bar(data = indi_17, aes(x = Start.Date),fill = '#6699CC')
g2_20 <- ggplot() + geom_bar(data = indi_20, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g2_21 <- ggplot() + geom_bar(data = indi_21, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g2_22 <- ggplot() + geom_bar(data = indi_22, aes(x = Start.Date),fill = '#6699CC') +
    geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
    geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#3.all aorr
aorr <- df %>% select(Start.Date, Application.or.Renewal)

aorr_0 <- aorr %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_17 <- aorr %>% filter(year(Start.Date) == 2017) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_18 <- aorr %>% filter(year(Start.Date) == 2018) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_19 <- aorr %>% filter(year(Start.Date) == 2019) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_20 <- aorr %>% filter(year(Start.Date) == 2020) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_21 <- aorr %>% filter(year(Start.Date) == 2021) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

aorr_22 <- aorr %>% filter(year(Start.Date) == 2022) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

g3_0 <- ggplot() + geom_bar(data = aorr_0, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g3_17 <- ggplot() + geom_bar(data = aorr_17, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g3_18 <- ggplot() + geom_bar(data = aorr_18, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g3_19 <- ggplot() + geom_bar(data = aorr_19, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g3_20 <- ggplot() + geom_bar(data = aorr_20, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g3_21 <- ggplot() + geom_bar(data = aorr_21, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g3_22 <- ggplot() + geom_bar(data = aorr_22, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#4.busi aorr
g4_0 <- ggplot() + geom_bar(data = busi_0, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g4_17 <- ggplot() + geom_bar(data = busi_17, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g4_18 <- ggplot() + geom_bar(data = busi_18, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g4_19 <- ggplot() + geom_bar(data = busi_19, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g4_20 <- ggplot() + geom_bar(data = busi_20, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g4_21 <- ggplot() + geom_bar(data = busi_21, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g4_22 <- ggplot() + geom_bar(data = busi_22, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#5.indi aorr
g5_0 <- ggplot() + geom_bar(data = indi_0, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g5_17 <- ggplot() + geom_bar(data = indi_17, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g5_18 <- ggplot() + geom_bar(data = indi_18, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g5_19 <- ggplot() + geom_bar(data = indi_19, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer()
g5_20 <- ggplot() + geom_bar(data = indi_20, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g5_21 <- ggplot() + geom_bar(data = indi_21, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g5_22 <- ggplot() + geom_bar(data = indi_22, aes(x = Start.Date, fill = Application.or.Renewal)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#6.all ac
ac <- df %>% select(Start.Date, Application.Category)

ac_0 <- ac %>% mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_17 <- ac %>% filter(year(Start.Date) == 2017) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_18 <- ac %>% filter(year(Start.Date) == 2018) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_19 <- ac %>% filter(year(Start.Date) == 2019) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_20 <- ac %>% filter(year(Start.Date) == 2020) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_21 <- ac %>% filter(year(Start.Date) == 2021) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

ac_22 <- ac %>% filter(year(Start.Date) == 2022) %>%
  mutate(Start.Date = format(as.Date(Start.Date),'%Y-%m'))

g6_0 <- ggplot() + geom_bar(data = ac_0, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g6_17 <- ggplot() + geom_bar(data = ac_17, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g6_18 <- ggplot() + geom_bar(data = ac_18, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g6_19 <- ggplot() + geom_bar(data = ac_19, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g6_20 <- ggplot() + geom_bar(data = ac_20, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g6_21 <- ggplot() + geom_bar(data = ac_21, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g6_22 <- ggplot() + geom_bar(data = ac_22, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#7.busi ac
g7_0 <- ggplot() + geom_bar(data = busi_0, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g7_17 <- ggplot() + geom_bar(data = busi_17, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g7_18 <- ggplot() + geom_bar(data = busi_18, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g7_19 <- ggplot() + geom_bar(data = busi_19, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g7_20 <- ggplot() + geom_bar(data = busi_20, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g7_21 <- ggplot() + geom_bar(data = busi_21, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g7_22 <- ggplot() + geom_bar(data = busi_22, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

```{r}
#8.indi ac
g8_0 <- ggplot() + geom_bar(data = indi_0, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_1, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_1, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

g8_17 <- ggplot() + geom_bar(data = indi_17, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g8_18 <- ggplot() + geom_bar(data = indi_18, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g8_19 <- ggplot() + geom_bar(data = indi_19, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer()
g8_20 <- ggplot() + geom_bar(data = indi_20, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_20, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_20, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g8_21 <- ggplot() + geom_bar(data = indi_21, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_21, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_21, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')
g8_22 <- ggplot() + geom_bar(data = indi_22, aes(x = Start.Date, fill = Application.Category)) + scale_fill_brewer() +
  geom_line(data = covid_22, aes(x = date, y = n, group = 1),size = 1.2, color = '#FFCC99')+
  geom_point(data = covid_22, aes(x = date, y = n, group = 1), size = 1.2, color = '#FFCC99')

```

